set (DK_QCC_ARCH               "gcc_ntoaarch64le")
set (CMAKE_SYSTEM_NAME         QNX)
set (CMAKE_CXX_STANDARD        11)
set (CMAKE_C_COMPILER          qcc.exe)
set (CMAKE_C_FLAGS             "${CMAKE_C_FLAGS} -lang-c -O0")
set (CMAKE_CXX_COMPILER        q++.exe)
set (CMAKE_CXX_FLAGS           "${CMAKE_CXX_FLAGS} -lang-c++ -O0")
set (CMAKE_C_COMPILER_TARGET   "${DK_QCC_ARCH}")
set (CMAKE_CXX_COMPILER_TARGET "${DK_QCC_ARCH}")
